### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by willemdh** [PFCKrutonium/SkypeAdvertRemover#1]
Hello,

It would be nice if a little 'how to' or link to some documentation on how to use this was included. 

Grtz

Willem

**Comment by Krutonium** [comment]
It's literally download the exe, and run it. It will patch the skype client for the current user, for anyone who has logged into skype as the current user.

If skype is open, it will close it, but other than that it takes but a split second.

**Comment by Krutonium** [comment]
I also updated the main project page;

https://github.com/PFCKrutonium/SkypeAdvertRemover

**Comment by willemdh** [comment]
Thanks PFCKrutonium! I'll try this asap.
